### ISSUE TITLE
Variable test in sections.yml doesn't conform to internal whitespace expectations

### ISSUE THREAD

**Issue by adam-fowler** [mustache/spec#117]
```yaml
- name: Variable test
    desc: |
      Non-false sections have their value at the top of context,
      accessible as {{.}} or through the parent context. This gives
      a simple way to display content conditionally if a variable exists.
    data: { foo: "bar" }
    template: '"{{#foo}} {{.}} is {{foo}} {{/foo}}"'
    expected: '"bar is bar"'
```
Should expected not be '" bar is bar "' ie with whitespace surrounding the "bar is bar" text, or am I missing something
