### ISSUE TITLE
Nested Behaviors

### ISSUE THREAD

**Issue by andrewthad** [mustache/spec#94]
This originally came up in an issue for a haskell mustache implementation, (https://github.com/JustusAdam/mustache/issues/6) but I will describe a simpler example here with language-agnostic terminology.

Suppose that I have data represented in YAML as follows:

```
people:
  - person_name: Andrew
    person_age: 24
    dogs:
      - dog_name: Rover
        dog_weight: 42
      - dog_name: Gnarles Barkley
        dog_weight: 10
  - person_name: Bob
    person_age: 63
    dogs:
      - dog_name: Trixie
      - dog_weight: 20
```

And a template that looks like this:

```
Everyone's dogs
{{people}}
{{dogs}}
The dog {{dog_name}} belongs to {{person_name}}.
{{/dogs}}
{{/people}}
```

The output I expect (modulo some newlines) is:

```
The dog Rover belongs to Andrew.
The dog Gnarles Barkley belongs to Andrew.
The dog Trixie belongs to Bob.
```

However, the [haskell mustache implementation](https://github.com/JustusAdam/mustache), which completely passes version 1.1.3 of the specs, would give me this:

```
The dog Rover belongs to .
The dog Gnarles Barkley belongs to .
The dog Trixie belongs to .
```

So, I propose adding a spec test that would assure that bound variables remain bound in a nested section. Please let me know if I can clarify this further.
